FROM node:alpine

COPY ./backend-example-docker /backend-example-docker
WORKDIR /backend-example-docker
EXPOSE 8000
RUN npm install && \
    adduser -S app && \
    chown -R app /backend-example-docker
CMD ["npm", "start"]
ENV FRONT_URL=http://localhost:5000
USER app
