FROM node:alpine
LABEL maintainer="pexea12"

COPY calculator /calculator
WORKDIR /calculator
RUN npm install && npm run build

FROM nginx:alpine
EXPOSE 80
COPY --from=0 /calculator/build /app
COPY ./part-3/3-07/nginx.conf /etc/nginx/nginx.conf

